Menu = nuke.menu('Viewer').addMenu("QuickCreate", icon="ROI.png") # <--- BUG HERE FOUNDRY!, this icon will be replaced by the first in the sub menu
Menu.addCommand( 'QuickCreate ROI', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("ROI")',icon='ROI.png') #Luckily we have added the same icon for the first item =)
Menu.addCommand( 'QuickCreate Cornerpin (From)', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("CornerpinFrom")',icon='CornerPin.png')
Menu.addCommand( 'QuickCreate Cornerpin (To)', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("CornerpinTo")',icon='CornerPin.png')
Menu.addCommand( 'QuickCreate Cornerpin (From and To)', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("CornerpinFromTo")',icon='CornerPin.png')
Menu.addCommand( 'QuickCreate Crop', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Crop")',icon='Crop.png')
Menu.addCommand( 'QuickCreate GridWarp', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("GridWarp")',icon='GridWarp.png')
Menu.addCommand( 'QuickCreate Keylight', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Keylight")',icon='Keylight.png')
Menu.addCommand( 'QuickCreate Radial', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Radial")',icon='Radial.png')
Menu.addCommand( 'QuickCreate Text', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Text")',icon='Text.png')
Menu.addCommand( 'QuickCreate Tracker', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Tracker")',icon='Tracker.png')
Menu.addCommand( 'QuickCreate Transform', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Transform")',icon='2D.png')