Menu = nuke.menu('Viewer').addMenu("QuickCreate", icon="ROI.png") # <--- BUG HERE FOUNDRY!, this icon will be replaced by the first in the sub menu
Menu.addCommand( '-> ROI', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("ROI")',icon='ROI.png') #Luckily we have added the same icon for the first item =)
Menu.addCommand( '-> Cornerpin (From)', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("CornerpinFrom")',icon='CornerPin.png')
Menu.addCommand( '-> Cornerpin (To)', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("CornerpinTo")',icon='CornerPin.png')
Menu.addCommand( '-> Cornerpin (From and To)', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("CornerpinFromTo")',icon='CornerPin.png')
Menu.addCommand( '-> Crop', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Crop")',icon='Crop.png')
Menu.addCommand( '-> GridWarp', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("GridWarp")',icon='GridWarp.png')
Menu.addCommand( '-> Keylight', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Keylight")',icon='Keylight.png')
Menu.addCommand( '-> Radial', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Radial")',icon='Radial.png')
Menu.addCommand( '-> Text', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Text")',icon='Text.png')
Menu.addCommand( '-> Tracker', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Tracker")',icon='Tracker.png')
Menu.addCommand( '-> Transform', 'import h_viewerShortcuts ; h_viewerShortcuts.CreateOnSelection("Transform")',icon='2D.png')